# Generated by Django 5.1.1 on 2024-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_myblogthree'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogthree',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
